package com.logistics.entity;

public class Count {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count.id
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count.station
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String station;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count.money_count
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String moneyCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count.id
     *
     * @return the value of count.id
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count.id
     *
     * @param id the value for count.id
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count.station
     *
     * @return the value of count.station
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count.station
     *
     * @param station the value for count.station
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count.money_count
     *
     * @return the value of count.money_count
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getMoneyCount() {
        return moneyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count.money_count
     *
     * @param moneyCount the value for count.money_count
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setMoneyCount(String moneyCount) {
        this.moneyCount = moneyCount == null ? null : moneyCount.trim();
    }
}