package com.logistics.entity;

import java.util.Date;

public class Invoice {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.id
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.note
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.send_name
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String sendName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.sendto_name
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String sendtoName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.send_start
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String sendStart;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.sendto_end
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String sendtoEnd;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.send_tel
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String sendTel;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.sendto_tel
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String sendtoTel;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.order_name
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String orderName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.order_number
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.order_weight
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String orderWeight;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.order_bulk
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String orderBulk;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.money
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.order_car
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private String orderCar;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.send_time
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invoice.state
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.id
     *
     * @return the value of invoice.id
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.id
     *
     * @param id the value for invoice.id
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.note
     *
     * @return the value of invoice.note
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.note
     *
     * @param note the value for invoice.note
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.send_name
     *
     * @return the value of invoice.send_name
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getSendName() {
        return sendName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.send_name
     *
     * @param sendName the value for invoice.send_name
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setSendName(String sendName) {
        this.sendName = sendName == null ? null : sendName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.sendto_name
     *
     * @return the value of invoice.sendto_name
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getSendtoName() {
        return sendtoName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.sendto_name
     *
     * @param sendtoName the value for invoice.sendto_name
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setSendtoName(String sendtoName) {
        this.sendtoName = sendtoName == null ? null : sendtoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.send_start
     *
     * @return the value of invoice.send_start
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getSendStart() {
        return sendStart;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.send_start
     *
     * @param sendStart the value for invoice.send_start
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setSendStart(String sendStart) {
        this.sendStart = sendStart == null ? null : sendStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.sendto_end
     *
     * @return the value of invoice.sendto_end
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getSendtoEnd() {
        return sendtoEnd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.sendto_end
     *
     * @param sendtoEnd the value for invoice.sendto_end
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setSendtoEnd(String sendtoEnd) {
        this.sendtoEnd = sendtoEnd == null ? null : sendtoEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.send_tel
     *
     * @return the value of invoice.send_tel
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getSendTel() {
        return sendTel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.send_tel
     *
     * @param sendTel the value for invoice.send_tel
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setSendTel(String sendTel) {
        this.sendTel = sendTel == null ? null : sendTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.sendto_tel
     *
     * @return the value of invoice.sendto_tel
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getSendtoTel() {
        return sendtoTel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.sendto_tel
     *
     * @param sendtoTel the value for invoice.sendto_tel
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setSendtoTel(String sendtoTel) {
        this.sendtoTel = sendtoTel == null ? null : sendtoTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.order_name
     *
     * @return the value of invoice.order_name
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.order_name
     *
     * @param orderName the value for invoice.order_name
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName == null ? null : orderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.order_number
     *
     * @return the value of invoice.order_number
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.order_number
     *
     * @param orderNumber the value for invoice.order_number
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.order_weight
     *
     * @return the value of invoice.order_weight
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getOrderWeight() {
        return orderWeight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.order_weight
     *
     * @param orderWeight the value for invoice.order_weight
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setOrderWeight(String orderWeight) {
        this.orderWeight = orderWeight == null ? null : orderWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.order_bulk
     *
     * @return the value of invoice.order_bulk
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getOrderBulk() {
        return orderBulk;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.order_bulk
     *
     * @param orderBulk the value for invoice.order_bulk
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setOrderBulk(String orderBulk) {
        this.orderBulk = orderBulk == null ? null : orderBulk.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.money
     *
     * @return the value of invoice.money
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.money
     *
     * @param money the value for invoice.money
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.order_car
     *
     * @return the value of invoice.order_car
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getOrderCar() {
        return orderCar;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.order_car
     *
     * @param orderCar the value for invoice.order_car
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setOrderCar(String orderCar) {
        this.orderCar = orderCar == null ? null : orderCar.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.send_time
     *
     * @return the value of invoice.send_time
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invoice.state
     *
     * @return the value of invoice.state
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public Integer getState() {
        return state;
    }

    public Date getSendTime() {
        return sendTime;
    }

    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invoice.state
     *
     * @param state the value for invoice.state
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }
}