package com.logistics.entity;

public class Limite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column limite.limite_id
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private Integer limiteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column limite.limite_grade
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private Integer limiteGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column limite.limite_admin
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    private Integer limiteAdmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column limite.limite_id
     *
     * @return the value of limite.limite_id
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public Integer getLimiteId() {
        return limiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column limite.limite_id
     *
     * @param limiteId the value for limite.limite_id
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setLimiteId(Integer limiteId) {
        this.limiteId = limiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column limite.limite_grade
     *
     * @return the value of limite.limite_grade
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public Integer getLimiteGrade() {
        return limiteGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column limite.limite_grade
     *
     * @param limiteGrade the value for limite.limite_grade
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setLimiteGrade(Integer limiteGrade) {
        this.limiteGrade = limiteGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column limite.limite_admin
     *
     * @return the value of limite.limite_admin
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public Integer getLimiteAdmin() {
        return limiteAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column limite.limite_admin
     *
     * @param limiteAdmin the value for limite.limite_admin
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setLimiteAdmin(Integer limiteAdmin) {
        this.limiteAdmin = limiteAdmin;
    }
}