package com.logistics.entity;

public class Rode {
    
    private Integer rodeId;

    private String rodeName;
    
    private String name;
    

    public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public Integer getRodeId() {
        return rodeId;
    }

   
    public void setRodeId(Integer rodeId) {
        this.rodeId = rodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rode.rode_name
     *
     * @return the value of rode.rode_name
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public String getRodeName() {
        return rodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rode.rode_name
     *
     * @param rodeName the value for rode.rode_name
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    public void setRodeName(String rodeName) {
        this.rodeName = rodeName == null ? null : rodeName.trim();
    }
}