package com.logistics.entity;

import java.util.Date;

public class UserOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.id
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_send
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    private String orderSend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.send_tel
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    private String sendTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.send_start
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    private String sendStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.sendto_end
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    private String sendtoEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_name
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    private String orderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_number
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_time
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_static
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    private Integer orderStatic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_sendto
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    private String orderSendto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.id
     *
     * @return the value of user_order.id
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.id
     *
     * @param id the value for user_order.id
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_send
     *
     * @return the value of user_order.order_send
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public String getOrderSend() {
        return orderSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_send
     *
     * @param orderSend the value for user_order.order_send
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public void setOrderSend(String orderSend) {
        this.orderSend = orderSend == null ? null : orderSend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.send_tel
     *
     * @return the value of user_order.send_tel
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public String getSendTel() {
        return sendTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.send_tel
     *
     * @param sendTel the value for user_order.send_tel
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public void setSendTel(String sendTel) {
        this.sendTel = sendTel == null ? null : sendTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.send_start
     *
     * @return the value of user_order.send_start
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public String getSendStart() {
        return sendStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.send_start
     *
     * @param sendStart the value for user_order.send_start
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public void setSendStart(String sendStart) {
        this.sendStart = sendStart == null ? null : sendStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.sendto_end
     *
     * @return the value of user_order.sendto_end
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public String getSendtoEnd() {
        return sendtoEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.sendto_end
     *
     * @param sendtoEnd the value for user_order.sendto_end
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public void setSendtoEnd(String sendtoEnd) {
        this.sendtoEnd = sendtoEnd == null ? null : sendtoEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_name
     *
     * @return the value of user_order.order_name
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_name
     *
     * @param orderName the value for user_order.order_name
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName == null ? null : orderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_number
     *
     * @return the value of user_order.order_number
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_number
     *
     * @param orderNumber the value for user_order.order_number
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_time
     *
     * @return the value of user_order.order_time
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_time
     *
     * @param orderTime the value for user_order.order_time
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_static
     *
     * @return the value of user_order.order_static
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public Integer getOrderStatic() {
        return orderStatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_static
     *
     * @param orderStatic the value for user_order.order_static
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public void setOrderStatic(Integer orderStatic) {
        this.orderStatic = orderStatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_sendto
     *
     * @return the value of user_order.order_sendto
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public String getOrderSendto() {
        return orderSendto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_sendto
     *
     * @param orderSendto the value for user_order.order_sendto
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    public void setOrderSendto(String orderSendto) {
        this.orderSendto = orderSendto == null ? null : orderSendto.trim();
    }
}