package com.logistics.dao;

import java.util.List;

import com.logistics.entity.Complain;

public interface ComplainMapper {
	 List<Complain> getallcomplain();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain
     *
     * @mbggenerated Thu Oct 18 10:23:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain
     *
     * @mbggenerated Thu Oct 18 10:23:35 CST 2018
     */
    int insert(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain
     *
     * @mbggenerated Thu Oct 18 10:23:35 CST 2018
     */
    int insertSelective(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain
     *
     * @mbggenerated Thu Oct 18 10:23:35 CST 2018
     */
    Complain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain
     *
     * @mbggenerated Thu Oct 18 10:23:35 CST 2018
     */
    int updateByPrimaryKeySelective(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain
     *
     * @mbggenerated Thu Oct 18 10:23:35 CST 2018
     */
    int updateByPrimaryKey(Complain record);
}