package com.logistics.dao;

import com.logistics.entity.Count;

public interface CountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int insert(Count record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int insertSelective(Count record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    Count selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int updateByPrimaryKeySelective(Count record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int updateByPrimaryKey(Count record);
}