package com.logistics.dao;

import com.logistics.entity.Limite;

public interface LimiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table limite
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int deleteByPrimaryKey(Integer limiteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table limite
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int insert(Limite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table limite
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int insertSelective(Limite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table limite
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    Limite selectByPrimaryKey(Integer limiteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table limite
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int updateByPrimaryKeySelective(Limite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table limite
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int updateByPrimaryKey(Limite record);
}