package com.logistics.dao;

import java.util.List;

import com.logistics.entity.Rode;

public interface RodeMapper {
	List<Rode> getAllRole();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rode
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int deleteByPrimaryKey(Integer rodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rode
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int insert(Rode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rode
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int insertSelective(Rode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rode
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    Rode selectByPrimaryKey(Integer rodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rode
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int updateByPrimaryKeySelective(Rode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rode
     *
     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
     */
    int updateByPrimaryKey(Rode record);
}