package com.logistics.dao;

import java.util.List;

import com.logistics.entity.UserQt;

public interface UserQtMapper {
	public UserQt login(UserQt userQt);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_qt
     *
     * @mbggenerated Fri Oct 19 18:19:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_qt
     *
     * @mbggenerated Fri Oct 19 18:19:40 CST 2018
     */
    int insert(UserQt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_qt
     *
     * @mbggenerated Fri Oct 19 18:19:40 CST 2018
     */
    int insertSelective(UserQt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_qt
     *
     * @mbggenerated Fri Oct 19 18:19:40 CST 2018
     */
    UserQt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_qt
     *
     * @mbggenerated Fri Oct 19 18:19:40 CST 2018
     */
    int updateByPrimaryKeySelective(UserQt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_qt
     *
     * @mbggenerated Fri Oct 19 18:19:40 CST 2018
     */
    int updateByPrimaryKey(UserQt record);
}