package com.logistics.dao;

import java.util.List;

import com.logistics.entity.UserOrder;

public interface UserOrderMapper {
	List<UserOrder>  getalluserorder();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    int insert(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    int insertSelective(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    UserOrder selectByPrimaryKey(Integer id);
    UserOrder getoneuserorder(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    int updateByPrimaryKeySelective(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated Tue Oct 16 17:25:50 CST 2018
     */
    int updateByPrimaryKey(UserOrder record);
}