package com.logistics.service;

import java.util.List;

import com.logistics.entity.Complain;

public interface ComplainService {
	  List<Complain> getallcomplain();
	  int deleteByPrimaryKey(Integer id);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table complain
	     *
	     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
	     */
	    int insert(Complain record);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table complain
	     *
	     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
	     */
	    int insertSelective(Complain record);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table complain
	     *
	     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
	     */
	    Complain selectByPrimaryKey(Integer id);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table complain
	     *
	     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
	     */
	    int updateByPrimaryKeySelective(Complain record);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table complain
	     *
	     * @mbggenerated Sat Oct 13 16:51:59 CST 2018
	     */
	    int updateByPrimaryKey(Complain record);
}
