package com.logistics.service;

import java.util.List;

import com.logistics.entity.Invoice;
import com.logistics.entity.StationInvoiceCount;

public interface InvoiceService {
    List<Invoice> getallinvoice();

    List<Invoice> getnoinvoice();

    /**
     * 统计所有分理处金额
     * 
     * @return
     */
    public List<StationInvoiceCount> getAllCount(String sendTime);

    /**
     * 动态条件查询所有
     */
    public List<StationInvoiceCount> getSomeCount(StationInvoiceCount count);

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invoice
     *
     * @mbggenerated Wed Oct 24 17:41:10 CST 2018
     */
    int insert(Invoice record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invoice
     *
     * @mbggenerated Wed Oct 24 17:41:10 CST 2018
     */
    int insertSelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invoice
     *
     * @mbggenerated Wed Oct 24 17:41:10 CST 2018
     */
    Invoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invoice
     *
     * @mbggenerated Wed Oct 24 17:41:10 CST 2018
     */
    int updateByPrimaryKeySelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invoice
     *
     * @mbggenerated Wed Oct 24 17:41:10 CST 2018
     */
    int updateByPrimaryKey(Invoice record);

}
