package com.logistics.service;

import java.util.List;
import java.util.Set;

import com.logistics.entity.WlAdmin;

public interface WlAdminService {
	/**
	 * 通过主键查询员工表及角色表属性
	 * @param wlId
	 * @return
	 */
	WlAdmin getWlAdminByPrimaryKey(Integer wlId);
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wl_admin
     *
     * @mbggenerated Thu Oct 18 10:06:56 CST 2018
     */
    int deleteByPrimaryKey(Integer wlId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wl_admin
     *
     * @mbggenerated Thu Oct 18 10:06:56 CST 2018
     */
    int insert(WlAdmin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wl_admin
     *
     * @mbggenerated Thu Oct 18 10:06:56 CST 2018
     */
    int insertSelective(WlAdmin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wl_admin
     *
     * @mbggenerated Thu Oct 18 10:06:56 CST 2018
     */
    WlAdmin selectByPrimaryKey(Integer wlId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wl_admin
     *
     * @mbggenerated Thu Oct 18 10:06:56 CST 2018
     */
    int updateByPrimaryKeySelective(WlAdmin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wl_admin
     *
     * @mbggenerated Thu Oct 18 10:06:56 CST 2018
     */

    /*
     * 修改
     */
    int updateByPrimaryKey(WlAdmin record);

    /*
     * 登陆
     */
    WlAdmin selectByName(String wlName);

    /**
     * 通过用户名得到当前用户角色
     */
    Set<String> getRole(String wlName);

    /**
     * 通过用户名得到当前用户权限
     */
    Set<String> getPermission(String wlName);
    /**
     * 查询所有及对应的角色
     */
    List<WlAdmin> selectAllEmp();
}